---
kind: pipeline
type: docker
name: build

steps:
  - name: lint
    image: golangci/golangci-lint:v1.43.0
    environment:
      GOFLAGS: -mod=vendor
      CGO_ENABLED: 0
    commands:
      - golangci-lint run

  - name: test
    image: golang:1.17.3-alpine
    environment:
      GOFLAGS: -mod=vendor
      CGO_ENABLED: 0
    commands:
      - go test ./...
