image: golangci/golangci-lint:v1.32.2

stages:
  - test

lint:
  stage: test
  tags:
    - docker
  script:
    - golangci-lint run

test-1.15:
  stage: test
  tags:
    - docker
  image: golang:1.15
  script:
    - go test -test.v ./...

test-1.14:
  stage: test
  tags:
    - docker
  image: golang:1.14
  script:
    - go test -test.v ./...

test-1.13:
  stage: test
  tags:
    - docker
  image: golang:1.13
  script:
    - go test -test.v ./...
