stages:
  - test

before_script:
  - mkdir -p ${GOPATH}/src/gitlab.com/pztrn/
  - ln -s $CI_PROJECT_DIR ${GOPATH}/src/gitlab.com/pztrn/sec
  - cd ${GOPATH}/src/gitlab.com/pztrn/sec

test:1.13:
  image: golang:1.13.0
  stage: test
  tags:
    - docker
  script:
    - pwd
    - go test -test.v -cover ./...

test:1.12:
  image: golang:1.12.9
  stage: test
  tags:
    - docker
  script:
    - pwd
    - go test -test.v -cover ./...

test:1.11:
  image: golang:1.11.13
  stage: test
  tags:
    - docker
  script:
    - pwd
    - go test -test.v -cover ./...

test:1.10:
  image: golang:1.10.8
  stage: test
  tags:
    - docker
  script:
    - pwd
    - go test -test.v -cover ./...

test:1.9:
  image: golang:1.9.7
  stage: test
  tags:
    - docker
  script:
    - pwd
    - go test -test.v -cover ./...